! ploDataElem is a post-processing software for T+H (TOUGH HYDRATE) program.
! It reads plot_data_elem file generated by T+H simulations and converts them
! vtu format. Which can then be visualized by usign PARAVIEW and other
! softwares.
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

!> authors: Vikas Sharma, Ph. D.
! date: 	27 Feb 2021
! summary: 	Data type to handle PlotDataElem file generated by T+H

MODULE PlotDataElem_Class
USE PENF
USE StringiFor
USE File_Class
IMPLICIT NONE

PRIVATE
INTEGER, PARAMETER :: LGT = KIND( .true. )
INTEGER, PARAMETER :: DFP  = SELECTED_REAL_KIND( 15, 307 )
INTEGER, PARAMETER :: I4B  = SELECTED_INT_KIND( 9 )
INTEGER, PARAMETER :: FILE_OPEN_ERROR = 1
INTEGER, PARAMETER :: MAX_LEN_BUFFER= 1000
INTEGER, PARAMETER :: MAX_VAR_NAME_ALLOWED = 100
CHARACTER( LEN = 300 )  :: ERRMSG_1 = "User has supplied more variable names than allowed (100 Variable names are allowed!!!)"
CHARACTER( LEN = 300 )  :: ERRMSG_2 = "In Plot_Data_Elem file total number of zone cannot be ZERO!!!)"


!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> authors: Vikas Sharma, Ph. D.
! date: 	27 Feb 2021
! summary: 	Data type for handling individual block in `Plot_Data_Elem`
!
!### Introduction
! This data type is developed to tackle individual data block in `Plot_Data_Elem` file
!

TYPE :: ScalarPlotDataElem_
  INTEGER( I4B ) :: tPoints
    !! Total number of points
  REAL( DFP ) :: time
    !! Current time
  CHARACTER( LEN = 5 ) :: Format
    !! Format
  REAL( DFP ), ALLOCATABLE :: xyz( :, : )
    !! xyz coordinates in xij format
  REAL( DFP ), ALLOCATABLE :: varValue( :, : )
    !! Value of variables
END TYPE ScalarPlotDataElem_

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> authors: Vikas Sharma, Ph. D.
! date: 	27 Feb 2021
! summary: 	This datatype represents the entire `Plot_Data_Elem` file.

TYPE :: PlotDataElem_
  TYPE( String ) :: varName( MAX_VAR_NAME_ALLOWED )
  INTEGER( I4B ) :: tVar
  INTEGER( I4B ) :: dim
    !! Dimension of the problem
  TYPE( ScalarPlotDataElem_ ), ALLOCATABLE :: zone( : )
    !! Zone wise data block
  TYPE( File_ ) :: aFile
    !! File object for `Plot_Data_Elem`
  LOGICAL :: isAxiSym
END TYPE PlotDataElem_

PUBLIC :: PlotDataElem_

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> authors: Vikas Sharma, Ph. D.
! date: 27 Feb 2021
! summary: This routine initiate the plotDataElem
!
!
!### Usage
!
!```fortran
!	Todo
!```

INTERFACE
MODULE SUBROUTINE init_plotDataElem( Obj, FileName, varName, dim, isAxiSym, &
  & tElements, ierr )
  TYPE( PlotDataElem_ ), INTENT( INOUT) :: Obj
    !! Instance
  TYPE( String ), INTENT( IN ) :: FileName( 3 )
    !! Name of `Plot_Data_Elem` file
    !! FileName(1) == PATH
    !! FileName(2) == FILENAME
    !! FileName(3) == EXTENSION (with dot(.) at front)
  TYPE( String ), INTENT( IN ) :: varName( : )
    !! list of variable names
  INTEGER( I4B ), INTENT( IN ) :: dim
    !! Dimension of the grid
  LOGICAL, INTENT( IN ) :: isAxiSym
    !! True if Axis-symmetric grid
  INTEGER( I4B ), OPTIONAL, INTENT( IN ) :: tElements
    !! Total number of elements in the grid
  INTEGER( I4B ), OPTIONAL, INTENT( OUT ) :: ierr
    !! error flag
END SUBROUTINE init_plotDataElem
END INTERFACE

INTERFACE Initiate
  MODULE PROCEDURE init_plotDataElem
END INTERFACE Initiate

PUBLIC :: Initiate

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> authors: Vikas Sharma, Ph. D.
! date: 	27 Feb 2021
! summary: 	This routine displays the contents of the instance of [[PlotDataElem_]]

INTERFACE
MODULE SUBROUTINE disp_plotDataElem( Obj, Msg, UnitNo )
  TYPE( PlotDataElem_ ), INTENT( IN ) :: Obj
  CHARACTER( LEN = * ), INTENT( IN ) :: Msg
  INTEGER( I4B ), OPTIONAL, INTENT( IN ) :: UnitNo
END SUBROUTINE disp_plotDataElem
END INTERFACE

INTERFACE Display
  MODULE PROCEDURE disp_plotDataElem
END INTERFACE Display

PUBLIC :: Display

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

!> authors: Vikas Sharma, Ph. D.
! date: 	27 Feb 2021
! summary: 	This subroutine writes the node data

INTERFACE
MODULE SUBROUTINE write_nodes( Obj, ZoneID, path, prefix )
  TYPE( PlotDataElem_ ), INTENT( IN ) :: Obj
    !! Instance
  INTEGER( I4B ), INTENT( IN ) :: ZoneID
    !! ID of the zone whose data will be saved on the external disk
  CHARACTER( LEN = * ), INTENT( IN ), OPTIONAL :: path
  CHARACTER( LEN = * ), INTENT( IN ), OPTIONAL :: prefix
END SUBROUTINE write_nodes
END INTERFACE

INTERFACE WriteNodes
  MODULE PROCEDURE write_nodes
END INTERFACE WriteNodes

PUBLIC :: WriteNodes

END MODULE PlotDataElem_Class