! plotDataElem is a post-processing software for T+H (TOUGH HYDRATE) program.
! It reads plot_data_elem file generated by T+H simulations and converts them
! vtu format. Which can then be visualized by usign PARAVIEW and other
! softwares.
!
! Copyright (C) 2020-2021  Vikas Sharma, Ph.D
!
! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https: //www.gnu.org/licenses/>
!

!> authors: Vikas Sharma, Ph. D.
! date: 27 Feb 2021
! summary:


!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

MODULE AUX_MODULE
IMPLICIT NONE

CONTAINS

SUBROUTINE WELCOME
WRITE( *, "(A)") " __        __   _                                                "
WRITE( *, "(A)") " \ \      / /__| | ___   ___ ___  _ __ ___   ___                 "
WRITE( *, "(A)") "  \ \ /\ / / _ \ |/ _ \ / __/ _ \| '_ ` _ \ / _ \                "
WRITE( *, "(A)") "  _\ V  V /  __/ | (_) | (_| (_) | | | | | |  __/                "
WRITE( *, "(A)") " | |\_/\_/ \___|_|\___/ \___\___/|_| |_| |_|\___|                "
WRITE( *, "(A)") " | __/ _ \                                                       "
WRITE( *, "(A)") " | || (_) |                                                      "
WRITE( *, "(A)") "  \__\___/                                                       "
WRITE( *, "(A)") "                                                                 "
WRITE(*,"(A)") ".______    __        ______   .___________.                           "
WRITE(*,"(A)") "|   _  \  |  |      /  __  \  |           |                           "
WRITE(*,"(A)") "|  |_)  | |  |     |  |  |  | `---|  |----`                           "
WRITE(*,"(A)") "|   ___/  |  |     |  |  |  |     |  |                                "
WRITE(*,"(A)") "|  |      |  `----.|  `--'  |     |  |                                "
WRITE(*,"(A)") "| _|      |_______| \______/      |__|                                "
WRITE(*,"(A)") " _______       ___   .___________.    ___                             "
WRITE(*,"(A)") "|       \     /   \  |           |   /   \                            "
WRITE(*,"(A)") "|  .--.  |   /  ^  \ `---|  |----`  /  ^  \                           "
WRITE(*,"(A)") "|  |  |  |  /  /_\  \    |  |      /  /_\  \                          "
WRITE(*,"(A)") "|  '--'  | /  _____  \   |  |     /  _____  \                         "
WRITE(*,"(A)") "|_______/ /__/     \__\  |__|    /__/     \__\                        "
WRITE(*,"(A)") " _______  __       _______ .___  ___.  _______ .__   __. .___________."
WRITE(*,"(A)") "|   ____||  |     |   ____||   \/   | |   ____||  \ |  | |           |"
WRITE(*,"(A)") "|  |__   |  |     |  |__   |  \  /  | |  |__   |   \|  | `---|  |----`"
WRITE(*,"(A)") "|   __|  |  |     |   __|  |  |\/|  | |   __|  |  . `  |     |  |     "
WRITE(*,"(A)") "|  |____ |  `----.|  |____ |  |  |  | |  |____ |  |\   |     |  |     "
WRITE(*,"(A)") "|_______||_______||_______||__|  |__| |_______||__| \__|     |__|     "
WRITE(*,"(A)") "                                                                      "
WRITE( *, * )
WRITE( *, * ) "========================================================================"
WRITE( *, "(3X,A)") "ploDataElem is a post-processing software for T+H (TOUGH + HYDRATE)."
WRITE( *, "(3X,A)") "It can read plot_data_elem file generated by T+H and translates them"
WRITE( *, "(3X,A)") "into vtu format."

CALL TIMESTAMP
WRITE( *, "(3X,A)" ) "Copyright (C) 2020-2021, Vikas Sharma, Ph.D"
WRITE( *, "(3X,A)" ) "Email: vickysharma0812@gmail.com"
WRITE( *, "(3X,A)" ) "Findme: https://github.com/vickysharma0812/plotDataElem"
PRINT*,""
PRINT*,""
END SUBROUTINE

!----------------------------------------------------------------------------
!
!----------------------------------------------------------------------------

SUBROUTINE TIMESTAMP
  ! Define Intent of dummy Variable
  CHARACTER (LEN = 8 ):: ampm
  INTEGER ::   d
  INTEGER ::   h
  INTEGER ::   m
  INTEGER ::   mm
  CHARACTER ( LEN = 9 ), PARAMETER, DIMENSION(12) :: month = (/ &
            'January  ', 'February ', 'March    ', 'April    ', &
            'May      ', 'June     ', 'July     ', 'August   ', &
            'September', 'October  ', 'November ', 'December ' /)
  INTEGER :: n
  INTEGER :: s
  INTEGER :: values(8)
  INTEGER :: y

  CALL date_and_time ( values = values )

  y = values(1)
  m = values(2)
  d = values(3)
  h = values(5)
  n = values(6)
  s = values(7)
  mm = values(8)

  IF ( h < 12 ) THEN
    ampm = 'AM'
  ELSE IF ( h == 12 ) THEN
    IF( n == 0 .and. s == 0 ) THEN
      ampm = 'Noon'
    ELSE
      ampm = 'PM'
    END IF
  ELSE
    h = h - 12
    IF ( h < 12 ) THEN
      ampm = 'PM'
    ELSE IF ( h == 12 ) THEN
      IF ( n == 0 .and. s == 0 ) THEN
        ampm = 'Midnight'
      ELSE
        ampm = 'AM'
      END IF
    END IF
  END IF

  WRITE( *, '(8x, i2,1x,a,1x,i4,2x,i2,a1,i2.2,a1,i2.2,a1,i3.3,1x,a)' ) &
  d, TRIM( month(m) ), y, h, ':', n, ':', s, '.', mm, TRIM( ampm )

END SUBROUTINE TIMESTAMP

END MODULE AUX_MODULE

PROGRAM MAIN
  USE PENF
  USE VTK_FORTRAN
  USE STRINGIFOR
  USE PLOTDATAELEM_CLASS
  USE TABLEDELAUNAY
  USE AUX_MODULE
  IMPLICIT NONE

  INTEGER, PARAMETER :: LGT = KIND( .true. )
  INTEGER, PARAMETER :: DFP  = SELECTED_REAL_KIND( 15, 307 )
  INTEGER, PARAMETER :: I4B  = SELECTED_INT_KIND( 9 )
  type( plotDataElem_ ) :: obj
  type( string ), allocatable :: varName( : )
  type( string ) :: fileName( 3 )
  integer, allocatable :: conn( :, : )
  integer, allocatable :: xml_conn( : )
  integer, allocatable :: xml_offset( : )
  integer( i1p ), allocatable :: cell_type( : )
  type( vtk_file ) :: a_vtk_file
  integer :: ierr
  integer :: ZoneID
  integer :: np
  integer :: nc
  integer :: i
  integer :: a
  integer :: b
  integer :: tvar
  integer :: telements
  integer :: dim
  character( len = 120 ) :: prefix
  character( LEN = 120 ) :: buffer
  logical :: isAxiSym
  real( dfp ), allocatable :: xyz( :, : )

  CALL WELCOME

  ! user input: ask for file path
  WRITE( *, "(A)" ) "Enter the PATH where Plot_Data_Elem File is located :: "
  READ( *, * ) buffer

  fileName(1) = string( trim( buffer ) )
  fileName(2) = string( "Plot_Data_Elem")
  fileName(3) = string( "" )

  ! ask for prefix
  WRITE( *, "(A)" ) "Enter Prefix: (Example: 'test')"
  READ( *, * ) prefix

  ! ask for the total number of variables
  WRITE( *, "(A)" ) "Enter total number of variables: (Example: 3)"
  READ( *, * ) tvar

  ALLOCATE( varName( tvar ) )

  IF( tvar .gt. 0 ) THEN
    DO i = 1, tvar
      WRITE( *, "(A)" ) "VARIABLE( " // trim( str( n = i , no_sign = .true. ) ) // " ): (Example: 'P')"
      READ( *, * ) buffer
      varName( i ) = String( trim( buffer ) )
    END DO
  END IF

  ! ask for the dim of problem
  WRITE( *, "(A)" ) "Enter dimension: (Example: 1)"
  READ( *, * ) dim

  WRITE( *, "(A)" ) "Axisymmetric? (Example: true)"
  READ( *, * ) isAxiSym

  ! Read the telements
  ! write( *, "(A)" ) "Enter the number of data to be read in each zone (example: 10)"
  ! write( *, "(A)" ) "Enter -1 if you want to read all data"
  ! read( *, * ) telements
  ! if( telements .lt. 0 ) then
  CALL Initiate( obj = obj, fileName = fileName, varName = varName, &
    & dim = dim, isAxiSym = isAxiSym )

  ! else
  !   call initiate( obj = obj, fileName = fileName, varName = varName, &
  !     & dim = dim, isAxiSym =isAxiSym,tElements = telements )
  ! end if

  WRITE( *, "(A)" ) "======================================"
  WRITE( *, "(A)" ) "An Instance of PlotDataElem is CREATED"
  WRITE( *, "(A)" ) "======================================"

  DO ZoneID = 1, SIZE( obj % zone )
    WRITE( *, "(A)" ) "MAKING ZONE " // &
      & trim( str( n = ZoneID , fm = '(I4.4)' ) )
    WRITE( *, "(A)" ) "..."

    ! make connectivity
    xyz = obj % zone( ZoneID ) % xyz( 1:3, : )
    CALL WriteElements( xyz( 1:2, : ), conn )

    ! post processing file
    filename( 1 ) = trim( prefix ) // "_" // &
      & trim( str( n = ZoneID, fm = '(I4.4)' ) ) // ".vtu"

    ierr = a_vtk_file % initialize( format = 'ASCII', &
      & filename = filename( 1 ) % Raw, &
      & mesh_topology = 'UnstructuredGrid' )

    np = Obj % zone( ZoneID ) % tPoints
    nc = SIZE( conn, 2 )

    ierr = a_vtk_file % xml_writer % write_piece( np = np, nc = nc )

    call a_vtk_file % xml_writer % write_start_tag(name='Points')
    ierr = a_vtk_file % xml_writer % write_dataarray(data_name='Points', x=xyz)

    call a_vtk_file % xml_writer % write_end_tag(name='Points')
    write( *, * ) "self % error ", a_vtk_file % xml_writer % error
    write( *, * ) "tPoints = ", size( xyz, 2 ), "np = ", np, "nc =", nc, "ierr = ", ierr

    if( allocated( xml_conn ) ) deallocate( xml_conn )
    allocate( xml_conn( 3 * nc ) )

    if( allocated( xml_offset ) ) deallocate( xml_offset )
    allocate( xml_offset( nc ) )

    if( allocated( cell_type ) ) deallocate( cell_type )
    allocate( cell_type( nc ) )

    do i = 1, nc
      a = 1 + ( i - 1 ) * 3
      b = a + 2
      xml_conn( a : b ) = conn( 1 : 3, i ) - 1
      if( i .eq. 1 ) then
        xml_offset( i ) = 3
      else
        xml_offset( i ) = xml_offset( i - 1 ) + 3
      end if
      cell_type( i ) = 5_i1p
    end do

    ierr = a_vtk_file % xml_writer % write_connectivity( nc = nc, &
      & connectivity = xml_conn, offset = xml_offset, cell_type = cell_type )

      ierr = a_vtk_file%xml_writer%write_dataarray(location='node', action='open')
      do i = 1, tvar
        ierr = a_vtk_file%xml_writer%write_dataarray( &
          & data_name = Obj % varName( i ) % Raw, &
          & x = Obj % zone( ZoneID ) % varValue( i, : ) )
      end do
      ierr = a_vtk_file%xml_writer%write_dataarray(location='node', action='close')
    ierr = a_vtk_file % xml_writer % write_piece( )
    ierr = a_vtk_file % finalize( )
  end do
end program main
